name: Discord CI/CD Ntifications
author: oscar@dolthub.com
decription: >
  Send notifications about

inputs:
  webhook-url:
    description: The Discord Webhook URL to send messsages to
    required: true
  notify-on-success:
    description: Send notification if the job is successful
    required: true
  job-status:
    description: Status of job pulled from job context
    required: true

runs:
  using: 'node12'
  main: 'index.js'
